package com.codelab.SilverAirline.services;

import com.codelab.SilverAirline.entities.Flight;
import com.codelab.SilverAirline.repository.FlightRepo;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Random;

@Service
@Transactional
@RequiredArgsConstructor
@Slf4j
public class FlightServiceImpl implements FlightService {
    @Autowired
    private FlightRepo flightRepo;

    public FlightServiceImpl(FlightRepo flightRep) {
        this.flightRepo = flightRep;
    }

    @Override
    public Flight bookAFlight(Flight flight) {
        flight.setFlightNumber(autoGeneratedFlightNumber());
        return flightRepo.save(flight);
    }

    @Override
    public List<Flight> getFlights() {
        return flightRepo.findAll();
    }

    @Override
    public Flight lookupFlight(String flightNumber) {

        return flightRepo.findByFlightNumber(flightNumber);
    }

    public String autoGeneratedFlightNumber(){

        String letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

        // Generate two random letters
        Random random = new Random();
        char letter1 = letters.charAt(random.nextInt(letters.length()));
        char letter2 = letters.charAt(random.nextInt(letters.length()));

        // Generate three random digits
        int digits = random.nextInt(1000); // Generates 0 to 999
        String formattedDigits = String.format("%03d", digits);

        // Combine letters and digits to form the code
        String generatedCode = "" + letter1 + letter2 +"-"+ formattedDigits;

        return generatedCode;

    }
}
